export const ProjectsArr = [
	{
		id: 0,
		img: "./src/images/Video Game Hub.png",
		title: "Video Game Hub",
		description: "If a dog chews shoes whose shoes does he choose?",
		link: "https://video-game-hub-il1q.vercel.app/",
		badges: [
			"VS Code",
			"React.ts",
			"TypeScript",
			"Rawg API",
			"Vite",
			"Chakra UI",
			"Vercel",
		],
	},
	{
		id: 1,
		img: "./src/images/Social Media Dashboard dark theme.png",
		title: "Social Media Dashboard",
		description: "If a dog chews shoes whose shoes does he choose?",
		link: "https://amazing-boba-8f87e3.netlify.app/",
		badges: ["VS Code", "HTML/CSS", "JavaScript", "Netlify"],
	},
	{
		id: 2,
		img: "./src/images/Chat App.png",
		title: "Chat App",
		description: "If a dog chews shoes whose shoes does he choose?",
		link: "https://celadon-chaja-ad048a.netlify.app/",
		badges: ["VS Code", "HTML/CSS", "Netlify"],
	},
	{
		id: 3,
		img: "./src/images/zenitsu.png",
		title: "No",
		description: "If a dog chews shoes whose shoes does he choose?",
		link: "hi",
		badges: [
			"VS Code",
			"React.js",
			"Vite",
			"Tailwind CSS",
			"Daisy UI",
			"Vercel",
		],
	},
];
