export const ProjectsArr = [
	{
		id: 0,
		img: "./src/images/gojo.jpg",
		title: "Timics Portfolio",
		description: "If a dog chews shoes whose shoes does he choose?",
		link: "hi",
		badges: [
			"VS Code",
			"React.js",
			"Vite",
			"Tailwind CSS",
			"Daisy UI",
			"Vercel",
		],
	},
	{
		id: 1,
		img: "./src/images/ino.webp",
		title: "Yes",
		description: "If a dog chews shoes whose shoes does he choose?",
		link: "hi",
		badges: [
			"VS Code",
			"React.js",
			"Vite",
			"Tailwind CSS",
			"Daisy UI",
			"Vercel",
		],
	},
	{
		id: 2,
		img: "./src/images/nezuko.jpg",
		title: "No",
		description: "If a dog chews shoes whose shoes does he choose?",
		link: "hi",
		badges: [
			"VS Code",
			"React.js",
			"Vite",
			"Tailwind CSS",
			"Daisy UI",
			"Vercel",
		],
	},
	{
		id: 3,
		img: "./src/images/zenitsu.png",
		title: "No",
		description: "If a dog chews shoes whose shoes does he choose?",
		link: "hi",
		badges: [
			"VS Code",
			"React.js",
			"Vite",
			"Tailwind CSS",
			"Daisy UI",
			"Vercel",
		],
	},
];
